object FormTest1: TFormTest1
  Left = 0
  Top = 0
  Caption = 'FormTest1'
  ClientHeight = 597
  ClientWidth = 1284
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -22
  Font.Name = 'Tahoma'
  Font.Style = []
  PixelsPerInch = 192
  TextHeight = 27
  object GroupBox11: TGroupBox
    AlignWithMargins = True
    Left = 12
    Top = 12
    Width = 1260
    Height = 573
    Hint = 'Kod_OKWED wrong hint'
    HelpType = htKeyword
    HelpKeyword = 'Kod_KWED2'
    Margins.Left = 12
    Margins.Top = 12
    Margins.Right = 12
    Margins.Bottom = 12
    Align = alClient
    Caption = 'Help && Hints'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -26
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 0
    ExplicitWidth = 1274
    ExplicitHeight = 574
    object Kod_OKWED: TCheckBox
      Left = 32
      Top = 32
      Width = 388
      Height = 68
      HelpType = htKeyword
      HelpKeyword = 'Kod_OKWED'
      Margins.Left = 12
      Margins.Top = 12
      Margins.Right = 12
      Margins.Bottom = 12
      Caption = '[Kod_OKWED]'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 0
    end
    object Kod_MKC: TEdit
      Left = 32
      Top = 124
      Width = 484
      Height = 39
      Hint = 'cxHint test'
      HelpType = htKeyword
      HelpKeyword = '!'#1054#1089#1085#1086#1074#1072#1085#1080#1077
      Margins.Left = 12
      Margins.Top = 12
      Margins.Right = 12
      Margins.Bottom = 12
      ParentCustomHint = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 1
      Text = '[!'#1054#1089#1085#1086#1074#1072#1085#1080#1077']'
    end
    object internalHelpViewerButton: TButton
      Left = 584
      Top = 126
      Width = 300
      Height = 72
      Margins.Left = 12
      Margins.Top = 12
      Margins.Right = 12
      Margins.Bottom = 12
      Caption = 'Internal'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -22
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      OnClick = internalHelpViewerButtonClick
    end
    object externalHelpViewerButton: TButton
      Left = 584
      Top = 30
      Width = 300
      Height = 72
      HelpType = htKeyword
      HelpKeyword = 'Kod_OKWED'
      Margins.Left = 12
      Margins.Top = 12
      Margins.Right = 12
      Margins.Bottom = 12
      Caption = 'External [Kod_OKWED]'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -26
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      OnClick = externalHelpViewerButtonClick
    end
  end
end
