object FormTest2: TFormTest2
  Left = 0
  Top = 0
  Caption = 'FormTest2'
  ClientHeight = 597
  ClientWidth = 1284
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -22
  Font.Name = 'Tahoma'
  Font.Style = []
  PixelsPerInch = 192
  TextHeight = 27
  object GroupBox2: TGroupBox
    AlignWithMargins = True
    Left = 12
    Top = 12
    Width = 1260
    Height = 573
    Margins.Left = 12
    Margins.Top = 12
    Margins.Right = 12
    Margins.Bottom = 12
    Align = alClient
    Caption = 'GroupBox2'
    TabOrder = 0
    ExplicitWidth = 1274
    ExplicitHeight = 574
    object Label1: TLabel
      Left = 64
      Top = 96
      Width = 75
      Height = 31
      Margins.Left = 12
      Margins.Top = 12
      Margins.Right = 12
      Margins.Bottom = 12
      Caption = 'Label2'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -26
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object CheckBox1: TCheckBox
      Left = 64
      Top = 260
      Width = 388
      Height = 68
      Margins.Left = 12
      Margins.Top = 12
      Margins.Right = 12
      Margins.Bottom = 12
      Caption = 'CheckBox1'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -26
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object Edit1: TEdit
      Left = 224
      Top = 90
      Width = 484
      Height = 39
      Margins.Left = 12
      Margins.Top = 12
      Margins.Right = 12
      Margins.Bottom = 12
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -26
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      Text = 'Edit1'
    end
    object generateHintMappingButton: TButton
      Left = 312
      Top = 258
      Width = 300
      Height = 72
      Margins.Left = 12
      Margins.Top = 12
      Margins.Right = 12
      Margins.Bottom = 12
      Caption = 'Generate mapping'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -26
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      OnClick = generateHintMappingButtonClick
    end
  end
end
